### ISSUE TITLE
pick无法使用多个选择器

### ISSUE THREAD

**Issue by cfan7777777** [mika-cn/maoxian-assistant#1]
只有第一个选择器起作用，是格式和hide不一样？

**Comment by cfan7777777** [comment]
比如
{
    "name" : "smzdm",
    "pattern" : "https://post.smzdm.com/p/*",
    "pick" : ["#articleId","#comment"]
  }
只有第一个选择器能够保存下来

**Comment by mika-cn** [comment]
抱歉，回覆晚了，當前 MaoXian 只能裁剪一個區域。所以如果 pick 參數有多個選擇器時，會按照順序查找，找到第一個元素後就停止查找。

你可以嘗試往外層選中，並用 hide 剔除掉不要的元素。

**Comment by cfan7777777** [comment]
以后会不会加上裁剪多个区域，选中外层有时候外层比内层大很多，还有背景色，裁剪出来很难看

**Comment by mika-cn** [comment]
额，裁剪多个区域的场景不是很多 （也许我是错的）。感觉支持多选区，除了增加复杂度，益处不是很大。
