### ISSUE TITLE
1月29更新之后无法保存

### ISSUE THREAD

**Issue by cfan7777777** [mika-cn/maoxian-assistant#2]
以前保存在右下脚会显示保存进度，很快保存完，现在点保存在右上角显示裁剪中就一直卡那了

**Comment by cfan7777777** [comment]
对了，保存工具用的是为知笔记qt版

**Comment by mika-cn** [comment]
0.1.48 版本有 Bug，0.1.49 版本已经修复， Chrome 可能还没有上线 （google 卡住发布流程，要求三个工作日，人工审）。
