### ISSUE TITLE
知乎-裁剪计划 

### ISSUE THREAD

**Issue by 4698to** [mika-cn/maoxian-assistant#6]
[
  {
    "name" : "zhizhu-question",
    "pattern" : "https://*.zhihu.com/question/*",
    "pick" : "div.QuestionAnswers-answers",
    "hide" : ["div.Popover12-toggle","div.Sticky"]
  }
]

我这个哪有问题呢  
案例链接
https://www.zhihu.com/question/39707398/answer/1202346354

**Comment by mika-cn** [comment]
你的這個 pattern 有問題，我覺得你可能要表達的是：`https://*.zhihu.com/question/` 或者是 `https://www.zhihu.com/question/`

還有，你給的三個選擇器中，只有 `div.Sticky` 能找到對應的元素。這個你還得仔細檢查一下。

最後提供一個知乎問答的例子，你可以在這個例子上改成你想要的：

```
[
  {
    "name" : "zhizhu-question",
    "pattern" : "https://*.zhihu.com/question/",
    "pick" : "div.QuestionAnswer-content",
    "hide" : ["div.Popover12-toggle","div.Sticky"]
  }
]
```

**Comment by 4698to** [comment]
裁剪时并不起作用

**Comment by mika-cn** [comment]
@4698to

我上面給出的那個例子，是使用你給我的那個網址（https://www.zhihu.com/question/39707398/answer/1202346354），測試的，是可以自動選中的，有一點需要提及：我是在禁用腳本的情況下訪問的這個網頁，這可能會導致我們測試結果不同（因爲在腳本的渲染下，網頁的結構和 class 屬性可能會有所不同）。

上面是可能導致不同的情況之一，你還需要確保你啓用了「毛線助手」，並且在保存修改後，刷新目標網頁進行測試。

另：我上條回覆給出的那個例子，只可作爲一個參考。最需要注意的地方就是 `pattern` 的值要對，這個「計劃」就會應用到網頁上去。至於其他的細節，對着[文檔](https://mika-cn.github.io/maoxian-web-clipper/assistant/index-zh-CN.html)細心一點，就能弄對的。

Gook luck ;)

**Comment by mika-cn** [comment]
請查看該[文檔](https://mika-cn.github.io/maoxian-web-clipper/assistant/index-zh-CN.html)。細心一點，可以成功的。

## 關於上次回覆的例子

那個例子我是有在你給出的那個鏈接（即： https://www.zhihu.com/question/39707398/answer/1202346354 ）上面測試過的。值得提及的是：我並沒有啓用腳本，你在啓用腳本的情況下，網頁的結構可能發生變化。所以那個例子只能作爲參考。

Good luck.

**Comment by mika-cn** [comment]
我已經針對知乎寫了幾個 Plan，你可以通過訂閱「公開的 Plan」獲取到。如果還有別的要補充的，再另開一個 issue 反饋，這個 Issue 我先關了。
